version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: RealEstateManagerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"  # Pulsar binary protocol
      - "8081:8081"  # Pulsar Admin REST API
    networks:
      - backend

volumes:
  postgres_data:
  
networks:
  backend: